version: "3.4"

services:
  friday:
    image: registry.23alice.duckdns.org/friday:latest
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile
      network: host
      platforms:
        - linux/amd64  # AMD64 타겟 플랫폼
      args:
        - TARGET=deploy
      labels:
        - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
  